# Generated by Django 2.2.4 on 2019-08-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jane',
            name='friend',
            field=models.CharField(default='Kevin', max_length=20),
        ),
    ]
